# 注册数量
count: 1

# 并发数 (1 为串行)
max_workers: 1

# 上传配置 CLIProxyAPI 0:False，1:True
upload: 0
upload_url: http://35.212.247.92:8317/v0/management/auth-files
upload_token: admin123456

# 邮箱服务配置 moe mail
email_api: https://mail.jntml.me
email_api_key: your_email_api_key
email_domain: jntml.me

# 是否输出日志到文件  0:False，1:True
log_to_file: 0

# register_token.py 输出的 accessToken 文件 (每行一个，相对路径基于脚本目录)
access_token_file: ac/tokens.txt
